function [phi1_out]=kdv_embedded_low_regularity_second_order(u_hat,h)
%% Embedded second order low-regularity integrator from
% From Y Wu, X Zhao BIT Numerical Mathematics (2022)
% 
% Input:    u_hat...value of (\hat{u}_n)_{n=-N/2+1}^{N/2} at time t_n
%           h...timestep

phi1_out=expmdx3(u_hat,h)+1/6*conv1(expmdx3(dx_inv(u_hat),h),expmdx3(dx_inv(u_hat),h))...
    -1/6*expmdx3(conv1(dx_inv(u_hat),dx_inv(u_hat)),h)...
    +1/18*mathbbP(conv1(expmdx3(dx_inv(u_hat),h),dx_inv(conv1(expmdx3(dx_inv(u_hat),h),expmdx3(dx_inv(u_hat),h)))))...
    -1/18*mathbbP(conv1(expmdx3(dx_inv(u_hat),h),expmdx3(dx_inv(conv1(dx_inv(u_hat),dx_inv(u_hat))),h)))...    
    +1/54*expmdx3(dx_inv(conv1(dx_inv(u_hat),conv1(dx_inv(u_hat),dx_inv(u_hat)))),h)...
    -1/54*dx_inv(conv1(expmdx3(dx_inv(u_hat),h),conv1(expmdx3(dx_inv(u_hat),h),expmdx3(dx_inv(u_hat),h))))...   
    +1/6*h*expmdx3(dx_inv(u_hat),h)*sum(flip(u_hat(1:end-1)).*u_hat(1:end-1))...
    -h/18*dx_inv(expmdx3(conv1(u_hat,conv1(u_hat,u_hat)),h))...
    +h/36*expmdx3(dx_inv(conv1(u_hat,conv1(u_hat,u_hat))),h)...
    -h/36*dx_inv(conv1(expmdx3(u_hat,h),conv1(expmdx3(u_hat,h),expmdx3(u_hat,h))));

end